In [2]:
import numpy as np

In [11]:
x_shape = (2, 3, 4, 4)
w_shape = (3, 3, 4, 4)
x = np.ones(x_shape)
w = np.ones(w_shape)
pad = 1
stride = 2

In [15]:
print(x.shape)
#print(x)

(2, 3, 4, 4)


In [20]:
N, C, H, W = x.shape
F, C, HH, WW = w.shape

# Padding the input
x_pad = np.zeros((N, C, H+(2*pad), W+(2*pad)))

for i in range(N):
    for j in range(C):
        x_pad[i,j,:,:] = np.pad(x[i,j,:,:], (pad, pad),'constant')
        
print(x_pad.shape)
print(x_pad[0,:,:,:])

(2, 3, 6, 6)
[[[0. 0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [12]:
Hprime = int(1 + (H + 2 * pad - HH) / stride)
Wprime = int(1 + (W + 2 * pad - WW) / stride)

print(Hprime, Wprime)

2 2


In [14]:
x_im2col = np.zeros((N, (HH * WW * C), (Hprime * Wprime)))

print(x_im2col.shape)
#print(x_im2col)

(2, 48, 4)


In [24]:
for i in range(N):
    ctr = 0
    for j in range(0, Hprime+1, stride):
        for k in range(0, Wprime+1, stride):
            x_im2col[i, :, ctr] = (x_pad[i, :, j:(j + HH), k:(k + WW)]).reshape(-1)
            ctr+=1
            
print(x_im2col.shape)
print(x_im2col)

(2, 48, 4)
[[[0. 0. 0. 1.]
  [0. 0. 1. 1.]
  [0. 0. 1. 1.]
  [0. 0. 1. 0.]
  [0. 1. 0. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 0. 1. 0.]
  [0. 1. 0. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 0. 1. 0.]
  [0. 1. 0. 0.]
  [1. 1. 0. 0.]
  [1. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 1.]
  [0. 0. 1. 1.]
  [0. 0. 1. 0.]
  [0. 1. 0. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 0. 1. 0.]
  [0. 1. 0. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 0. 1. 0.]
  [0. 1. 0. 0.]
  [1. 1. 0. 0.]
  [1. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 1.]
  [0. 0. 1. 1.]
  [0. 0. 1. 0.]
  [0. 1. 0. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 0. 1. 0.]
  [0. 1. 0. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 0. 1. 0.]
  [0. 1. 0. 0.]
  [1. 1. 0. 0.]
  [1. 1. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 0. 1. 1.]
  [0. 0. 1. 1.]
  [0. 0. 1. 0.]
  [0. 1. 0. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 0. 1. 0.]
  [0. 1. 0. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 0. 1. 0.]
  [0. 1. 0. 0.]
  [1. 1. 0.

In [33]:
for i in range(2):
    print(i)

0
1


In [29]:
a = [1,2,3,4]
print(a)

[1, 2, 3, 4]


In [31]:
print(a[1:3])

[2, 3]


In [35]:
a = np.zeros((2,3))
for i in range(2):
    a += np.ones((2,3))
    
print(a)

[[2. 2. 2.]
 [2. 2. 2.]]


In [42]:
x_shape = (2,3,4,4)
x = np.ones(x_shape)
a = np.sum(x, axis=0)
print(a.shape)
a = np.sum(x, axis=1)
print(a.shape)
a = np.sum(x, axis=(2,3))
print(a.shape)
a = np.sum(x, axis=3)
print(a.shape)

(3, 4, 4)
(2, 4, 4)
(2, 3)
(2, 3, 4)


In [8]:
import numpy as np
a = (12, 23, 45)
b = np.zeros((3,), dtype=int)
print(b[1])
c = 1
print(c)

0
1


In [18]:
a = ((np.zeros(4,))*2)
print(a)

[0. 0. 0. 0.]


In [32]:
shape = (2,3,5,5)
a = np.zeros(shape)
print(a.shape)

a = np.transpose(a, axes=[1,0,2,3])
print(a.shape)
b = a
print(b.shape)
b = np.transpose(b, axes=[1,0,2,3])
print(b.shape)

(2, 3, 5, 5)
(3, 2, 5, 5)
(3, 2, 5, 5)
(2, 3, 5, 5)


In [36]:
a = (1,2,3,4,5,6,7)
print(a[0:3])
print(a[3:6])

(1, 2, 3)
(4, 5, 6)


In [2]:
import tensorflow as tf

cifar100 = tf.keras.datasets.cifar100.load_data()
(X_train, y_train), (X_test, y_test) = cifar100

print('Train data shape: ', X_train.shape)
print('Train labels shape: ', y_train.shape, y_train.dtype)
print('Test data shape: ', X_test.shape)
print('Test labels shape: ', y_test.shape)

Train data shape:  (50000, 32, 32, 3)
Train labels shape:  (50000, 1) int64
Test data shape:  (10000, 32, 32, 3)
Test labels shape:  (10000, 1)


In [4]:
import tensorflow as tf
print(tf._version_)

AttributeError: module 'tensorflow' has no attribute '_version_'

In [6]:
a = ((1,))
#print(a.shape)
print(len(a))

1
